version: '3.5'

services:

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5432:5432"

  api:
    container_name: api
    restart: always
    build:
      context: ./netflix_app
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./netflix_app:/usr/src/netflix_app
    depends_on:
      - "postgres"
