"""empty message

Revision ID: b38357d2db96
Revises: cf47a26f5823
Create Date: 2020-09-21 12:32:20.238814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38357d2db96'
down_revision = 'cf47a26f5823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode_comments', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode_comments', 'updated_on')
    # ### end Alembic commands ###
